### ISSUE TITLE
Cannot pass negative doubles

### ISSUE THREAD

**Issue by brianharwell** [Tyrrrz/CliFx#88]
I have a simple command...
```
[Command("calculate")]
    public class Calculate : ICommand
    {
        [CommandParameter(0, Name = "Latitude")]
        public double Latitude { get; set; }

        [CommandParameter(1, Name = "Longitude")]
        public double Longitude { get; set; }

        public ValueTask ExecuteAsync(IConsole console)
        {
            System.Console.WriteLine($"Latitude: {Latitude}");
            System.Console.WriteLine($"Longitude: {Longitude}");

            return default;
        }
    }
```

If I pass positive values it works...
```
.\Console.exe calculate 1 3
Latitude: 1
Longitude: 3

.\Console.exe calculate 1.6675 3.7655676
Latitude: 1.6675
Longitude: 3.7655676
```

If I pass negative numbers it fails...
```
.\Console.exe calculate -1.6675 -3.7655676
Missing value for parameter <Latitude>.
```

**Comment by brianharwell** [comment]
Even attempting to pass as strings fails...
```
.\Console.exe calculate "-1.6675" "-3.7655676"
Missing value for parameter <Latitude>.
```

**Comment by adambajguz** [comment]
hi, this is sth I have fixed in [Typin](https://github.com/adambajguz/Typin/wiki/Argument-syntax). @Tyrrrz feel free to copy my idea. 

PS. `develop` branch has a 3.0 developer preview version that has a much cleaner code than on `master`.

**Comment by brianharwell** [comment]
Sweet thanks!

**Comment by Tyrrrz** [comment]
Np. I'll try to release a new version next week

**Comment by brianharwell** [comment]
@Tyrrrz Would you please cut a release with this fix?

**Comment by brianharwell** [comment]
@Tyrrrz i thought it might so I updated and the parsing still fails

**Comment by Tyrrrz** [comment]
@brianharwell can you share a command that fails? maybe i missed some edge case

**Comment by Tyrrrz** [comment]
@brianharwell glad to hear!
